Repository hmcts/et-sya-api, pull requests merged in 2022-08, with the labels that each got.

#108 Added Fortify nightly pipeline integration
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:et, prd:et, rel:et-sya-api-pr-108

#109 Ret 2118 add fortify nightly pipeline integration
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-api-pr-109

#111 RET-1974. Update et-data-model version.
  build.gradle
Labels: ns:et, prd:et, rel:et-sya-api-pr-111

#106 Ret 2128 - Create PdfMapperService
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfMapperConstants.java
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfMapperService.java
  src/main/resources/ET1_0722.pdf
  src/test/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfMapperServiceTest.java
  src/test/resources/responses/pdfMapperCaseDetails.json
Labels: ns:et, prd:et, rel:et-sya-api-pr-106

#112 Point idam api to correct port
  src/main/resources/application.yaml
Labels: ns:et, prd:et, rel:et-sya-api-pr-112

#110 Ret 2011 - add 'CaseData to Pdf' conversion service
  build.gradle
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfService.java
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfServiceException.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfServiceTest.java
  src/test/resources/ET1_0722.pdf
Labels: ns:et, prd:et, rel:et-sya-api-pr-110

#113 Bump et-data-model
  build.gradle
Labels: ns:et, prd:et, rel:et-sya-api-pr-113

#114 Add backstage configuration file
  catalog-info.yaml
Labels: ns:et, prd:et, rel:et-sya-api-pr-114
