Repository hmcts/et-sya-api, pull requests merged in 2023-08, with the labels that each got.

#422 Upgrade: java-logging 6.0.1
  build.gradle
Labels: ns:et, prd:et, rel:et-sya-api-pr-422

#423 Update tags
  infrastructure/main.tf
Labels: ns:et, prd:et, add-or-update, rel:et-sya-api-pr-423

#424 Update aat staging tag
  infrastructure/main.tf
Labels: ns:et, prd:et, add-or-update, rel:et-sya-api-pr-424

#428 RET-4060 Update IDAM port to 5062
  src/main/resources/application-cftlib.yaml
Labels: ns:et, prd:et, rel:et-sya-api-pr-428

#434 date formatting fix
  src/main/java/uk/gov/hmcts/reform/et/syaapi/constants/EtSyaConstants.java
  src/main/java/uk/gov/hmcts/reform/et/syaapi/helper/TseApplicationHelper.java
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/et/syaapi/helper/TseApplicationHelperTest.java
  src/test/java/uk/gov/hmcts/reform/et/syaapi/service/NotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-sya-api-pr-434

#443 RET-3899
  src/main/java/uk/gov/hmcts/reform/et/syaapi/helper/NotificationsHelper.java
  src/test/java/uk/gov/hmcts/reform/et/syaapi/helper/NotificationHelperTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-sya-api-pr-443

#478 missing fields value added in pdf generated
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfService.java
  src/test/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfServiceTest.java
Labels: ns:et, prd:et, rel:et-sya-api-pr-478
